#!/bin/bash
DAEMON="/opt/willy/components/speech_recognition/start_recognition.sh"
PIDFILE=/var/run/speech_recognition.pid

case "$1" in
  start)
     log_daemon_msg "Starting speech_recognition"
     start_daemon -p $PIDFILE $DAEMON
     log_end_msg $?
   ;;
  stop)
     log_daemon_msg "Stopping speech_recognition"
     killproc -p $PIDFILE $DAEMON
     PID=`ps x |grep feed | head -1 | awk '{print $1}'`
     kill -9 $PID
     log_end_msg $?
   ;;
  force-reload|restart)
     $0 stop
     $0 start
   ;;
  status)
     status_of_proc -p $PIDFILE $DAEMON atd && exit 0 || exit $?
   ;;
 *)
   echo "Usage: START {start|stop|restart|force-reload|status}"
   exit 1
  ;;
esac

exit 0
