#!/bin/bash
DIR=/opt/willy/components/speech_recognition
DAEMON=$DIR/start_recognition.sh
DAEMON_NAME=speech_recognition
DAEMON_OPTS=""
SPEECH_LOG=/var/log/speech_recognition.log
SPEECH_ERR=/var/log/speech_recognition.err

PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

date >> $ROSCORE_LOG
date >> $ROSCORE_ERR
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_ARGS 1>> $SPEECH_LOG 2>>$SPEECH_ERR </dev/null || return 2
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: ./START {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
